//! Commit origin: AI-coauthored or human. "Is AI making our codebase worse?" is the question
//! behind every other one, and it is answerable from commit metadata alone — coding agents
//! sign their work with `Co-authored-by` trailers, bot identities and message markers.
//! Nothing here is a heuristic over the code; a commit is AI-coauthored only when it says
//! so, which under-counts (a developer who strips the trailer is human) and never invents.

use serde::{Deserialize, Serialize};

/// Who authored a commit, as far as its metadata says.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default, Serialize, Deserialize,
)]
#[serde(rename_all = "snake_case")]
pub enum Origin {
    #[default]
    Human,
    Ai,
}

impl Origin {
    pub fn as_str(self) -> &'static str {
        match self {
            Origin::Human => "human",
            Origin::Ai => "ai",
        }
    }
}

/// The signals that mark a commit as AI-coauthored. Every list is matched case-insensitively
/// as a substring; the defaults cover the agents that sign their commits today and a team
/// adds its own bot identities or message conventions.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AttributionConfig {
    /// Substrings of an author or co-author *email* that mark an AI (e.g. `noreply@anthropic.com`).
    pub ai_emails: Vec<String>,
    /// Substrings of an author or co-author *name* that mark an AI (e.g. `copilot`).
    pub ai_names: Vec<String>,
    /// Substrings anywhere in the commit message that mark an AI (e.g. `Generated with`).
    pub ai_markers: Vec<String>,
}

impl Default for AttributionConfig {
    fn default() -> Self {
        AttributionConfig {
            ai_emails: [
                "noreply@anthropic.com",
                "copilot@github.com",
                "cursoragent",
                "devin-ai-integration",
                "aider@",
                "codex@openai.com",
                "chatgpt@openai.com",
                "jules@google.com",
                "sweep-ai",
            ]
            .iter()
            .map(|s| s.to_string())
            .collect(),
            ai_names: [
                "claude",
                "copilot",
                "cursor agent",
                "devin",
                "aider",
                "codex",
                "chatgpt",
                "gemini",
                "jules",
                "sweep ai",
                "openhands",
            ]
            .iter()
            .map(|s| s.to_string())
            .collect(),
            ai_markers: [
                "🤖 generated with",
                "generated with claude",
                "generated by copilot",
                "made with cursor",
                "claude-session:",
                "[ai-generated]",
                "[ai]",
            ]
            .iter()
            .map(|s| s.to_string())
            .collect(),
        }
    }
}

/// Classify a commit from its author identity and full message (trailers included).
pub fn classify(
    cfg: &AttributionConfig,
    author_name: &str,
    author_email: &str,
    message: &str,
) -> Origin {
    let lower = |s: &str| s.to_ascii_lowercase();
    let name = lower(author_name);
    let email = lower(author_email);
    let msg = lower(message);
    let hit_email = |e: &str| {
        cfg.ai_emails
            .iter()
            .any(|m| !m.is_empty() && e.contains(&lower(m)))
    };
    let hit_name = |n: &str| {
        cfg.ai_names
            .iter()
            .any(|m| !m.is_empty() && n.contains(&lower(m)))
    };
    if hit_email(&email) || hit_name(&name) {
        return Origin::Ai;
    }
    // Trailers: `Co-authored-by: Name <email>` lines anywhere in the message.
    for line in msg.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("co-authored-by:") {
            let rest = rest.trim();
            let (n, e) = match rest.split_once('<') {
                Some((n, e)) => (n.trim(), e.trim_end_matches('>').trim()),
                None => (rest, ""),
            };
            if hit_email(e) || hit_name(n) {
                return Origin::Ai;
            }
        }
    }
    if cfg
        .ai_markers
        .iter()
        .any(|m| !m.is_empty() && msg.contains(&lower(m)))
    {
        return Origin::Ai;
    }
    Origin::Human
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trailers_bot_identities_and_markers_mark_ai_and_nothing_else_does() {
        let cfg = AttributionConfig::default();
        assert_eq!(
            classify(&cfg, "Nick", "nick@example.com", "fix: typo"),
            Origin::Human
        );
        assert_eq!(
            classify(
                &cfg,
                "Nick",
                "nick@example.com",
                "feat: x\n\nCo-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>\n"
            ),
            Origin::Ai
        );
        assert_eq!(
            classify(
                &cfg,
                "Nick",
                "nick@example.com",
                "x\n\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>"
            ),
            Origin::Ai
        );
        assert_eq!(
            classify(&cfg, "Cursor Agent", "cursoragent@cursor.com", "x"),
            Origin::Ai
        );
        assert_eq!(
            classify(
                &cfg,
                "Nick",
                "nick@example.com",
                "x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"
            ),
            Origin::Ai
        );
        assert_eq!(
            classify(&cfg, "Claudette", "claudette@example.com", "x"),
            Origin::Ai,
            "name substring matches — a team can narrow the list"
        );
        assert_eq!(
            classify(
                &cfg,
                "Nick",
                "nick@example.com",
                "x\n\nCo-authored-by: Pat <pat@example.com>"
            ),
            Origin::Human
        );
    }

    #[test]
    fn a_custom_config_replaces_the_defaults() {
        let cfg = AttributionConfig {
            ai_emails: vec!["bot@corp.example".into()],
            ai_names: Vec::new(),
            ai_markers: vec!["[agent]".into()],
        };
        assert_eq!(
            classify(&cfg, "Claude", "noreply@anthropic.com", "x"),
            Origin::Human
        );
        assert_eq!(
            classify(&cfg, "Nick", "nick@corp.example", "[agent] refactor"),
            Origin::Ai
        );
        assert_eq!(classify(&cfg, "Bot", "bot@corp.example", "x"), Origin::Ai);
    }
}
